# Render Blueprint para COSTAR Generator
services:
  - type: web
    name: costar-generator
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/status/health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      # Variáveis de ambiente serão configuradas no dashboard do Render
      # Não adicione valores sensíveis aqui
    autoDeploy: true
