services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.demo
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      - redis
    volumes:
      - ../backups:/app/backups
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ../frontend/sw.js:/usr/share/nginx/html/sw.js:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis_data:
